package dev.mccue.resolve.core.compatibility;

import dev.mccue.resolve.doc.Coursier;

import java.util.Map;

@Coursier("https://github.com/coursier/coursier/blob/f5f0870c7420fcb75de2466afe913217304bc5f1/modules/core/jvm/src/main/scala/coursier/core/compatibility/Entities.scala")
public final class Entities {
    private Entities() {}

    public static final Map<String, String> ENTITIES =
            Map.<String, String>ofEntries(
                    Map.entry("&nbsp;", "&#160;"),
                    Map.entry("&iexcl;", "&#161;"),
                    Map.entry("&cent;", "&#162;"),
                    Map.entry("&pound;", "&#163;"),
                    Map.entry("&curren;", "&#164;"),
                    Map.entry("&yen;", "&#165;"),
                    Map.entry("&brvbar;", "&#166;"),
                    Map.entry("&sect;", "&#167;"),
                    Map.entry("&uml;", "&#168;"),
                    Map.entry("&copy;", "&#169;"),
                    Map.entry("&ordf;", "&#170;"),
                    Map.entry("&laquo;", "&#171;"),
                    Map.entry("&not;", "&#172;"),
                    Map.entry("&shy;", "&#173;"),
                    Map.entry("&reg;", "&#174;"),
                    Map.entry("&macr;", "&#175;"),
                    Map.entry("&deg;", "&#176;"),
                    Map.entry("&plusmn;", "&#177;"),
                    Map.entry("&acute;", "&#180;"),
                    Map.entry("&micro;", "&#181;"),
                    Map.entry("&para;", "&#182;"),
                    Map.entry("&middot;", "&#183;"),
                    Map.entry("&cedil;", "&#184;"),
                    Map.entry("&ordm;", "&#186;"),
                    Map.entry("&raquo;", "&#187;"),
                    Map.entry("&iquest;", "&#191;"),
                    Map.entry("&Agrave;", "&#192;"),
                    Map.entry("&Aacute;", "&#193;"),
                    Map.entry("&Acirc;", "&#194;"),
                    Map.entry("&Atilde;", "&#195;"),
                    Map.entry("&Auml;", "&#196;"),
                    Map.entry("&Aring;", "&#197;"),
                    Map.entry("&AElig;", "&#198;"),
                    Map.entry("&Ccedil;", "&#199;"),
                    Map.entry("&Egrave;", "&#200;"),
                    Map.entry("&Eacute;", "&#201;"),
                    Map.entry("&Ecirc;", "&#202;"),
                    Map.entry("&Euml;", "&#203;"),
                    Map.entry("&Igrave;", "&#204;"),
                    Map.entry("&Iacute;", "&#205;"),
                    Map.entry("&Icirc;", "&#206;"),
                    Map.entry("&Iuml;", "&#207;"),
                    Map.entry("&ETH;", "&#208;"),
                    Map.entry("&Ntilde;", "&#209;"),
                    Map.entry("&Ograve;", "&#210;"),
                    Map.entry("&Oacute;", "&#211;"),
                    Map.entry("&Ocirc;", "&#212;"),
                    Map.entry("&Otilde;", "&#213;"),
                    Map.entry("&Ouml;", "&#214;"),
                    Map.entry("&times;", "&#215;"),
                    Map.entry("&Oslash;", "&#216;"),
                    Map.entry("&Ugrave;", "&#217;"),
                    Map.entry("&Uacute;", "&#218;"),
                    Map.entry("&Ucirc;", "&#219;"),
                    Map.entry("&Uuml;", "&#220;"),
                    Map.entry("&Yacute;", "&#221;"),
                    Map.entry("&THORN;", "&#222;"),
                    Map.entry("&szlig;", "&#223;"),
                    Map.entry("&agrave;", "&#224;"),
                    Map.entry("&aacute;", "&#225;"),
                    Map.entry("&acirc;", "&#226;"),
                    Map.entry("&atilde;", "&#227;"),
                    Map.entry("&auml;", "&#228;"),
                    Map.entry("&aring;", "&#229;"),
                    Map.entry("&aelig;", "&#230;"),
                    Map.entry("&ccedil;", "&#231;"),
                    Map.entry("&egrave;", "&#232;"),
                    Map.entry("&eacute;", "&#233;"),
                    Map.entry("&ecirc;", "&#234;"),
                    Map.entry("&euml;", "&#235;"),
                    Map.entry("&igrave;", "&#236;"),
                    Map.entry("&iacute;", "&#237;"),
                    Map.entry("&icirc;", "&#238;"),
                    Map.entry("&iuml;", "&#239;"),
                    Map.entry("&eth;", "&#240;"),
                    Map.entry("&ntilde;", "&#241;"),
                    Map.entry("&ograve;", "&#242;"),
                    Map.entry("&oacute;", "&#243;"),
                    Map.entry("&ocirc;", "&#244;"),
                    Map.entry("&otilde;", "&#245;"),
                    Map.entry("&ouml;", "&#246;"),
                    Map.entry("&divide;", "&#247;"),
                    Map.entry("&oslash;", "&#248;"),
                    Map.entry("&ugrave;", "&#249;"),
                    Map.entry("&uacute;", "&#250;"),
                    Map.entry("&ucirc;", "&#251;"),
                    Map.entry("&uuml;", "&#252;"),
                    Map.entry("&yacute;", "&#253;"),
                    Map.entry("&thorn;", "&#254;"),
                    Map.entry("&yuml;", "&#255;")
            );
}
